#   Config files for pyMP3duplicates.py
#
#   Use single quotes :-(
#
#   March 2020   Kevin Scott


title = 'pyMP3duplicates config file'

# version information
[INFO]
myVERSION = '1.0.8'
myNAME    = 'pyMP3duplicate'

[TQDM]
ncols = 160     # Width of progress bar, should be equal or smaller then width of command window.
