#   Config files for pyMP3duplicates.py
#
#   true and false are lowe case
#   Config files for pyMP3duplicates.py
#   location needs double \ i.e. c:\tmp\music - well, on windows any way.
#
#   March 2020    (c) Kevin Scott

[INFO]
myVERSION = "2020.26"
myNAME = "pyMP3duplicate"

[APPLICATION]
notification=true

[TQDM]
ncols = 160

[TAGS]
module = "TinyTag"
ignore = "**IGNORE**"
soundex = true

[DATABASE]
format = "pickle"
filename = "dup"
location = ""              #  if used, remember a trail slash \.
overwrite = false

[ZAP]
recycle = true

