#   Configure files for pyMP3duplicates.py
#
#   true and false are lower case
#   Configure files for pyMP3duplicates.py
#   location needs double \ i.e. c:\tmp\music - well, on windows any way.
#
#   Copyright (C) <2020-2021>  <Kevin Scott>

[INFO]
myVERSION = "2021.37"
myNAME = "pyMP3duplicate"

[APPLICATION]
notification = true

[TQDM]
ncols = 160

[TAGS]
module = "tinytag"
ignore = "**IGNORE**"
soundex = true

[DATABASE]
format = "pickle"
filename = "dup"
location = ""
overwrite = false

[ZAP]
recycle = true
emptyDir = true
